/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as NearbyFacilitiesRouteImport } from './routes/nearby-facilities'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LiveMapRouteImport } from './routes/live-map'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as EmergencyInfoRouteImport } from './routes/emergency-info'
import { Route as IndexRouteImport } from './routes/index'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const NearbyFacilitiesRoute = NearbyFacilitiesRouteImport.update({
  id: '/nearby-facilities',
  path: '/nearby-facilities',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveMapRoute = LiveMapRouteImport.update({
  id: '/live-map',
  path: '/live-map',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyInfoRoute = EmergencyInfoRouteImport.update({
  id: '/emergency-info',
  path: '/emergency-info',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/emergency-info': typeof EmergencyInfoRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/live-map': typeof LiveMapRoute
  '/login': typeof LoginRoute
  '/nearby-facilities': typeof NearbyFacilitiesRoute
  '/signup': typeof SignupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/emergency-info': typeof EmergencyInfoRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/live-map': typeof LiveMapRoute
  '/login': typeof LoginRoute
  '/nearby-facilities': typeof NearbyFacilitiesRoute
  '/signup': typeof SignupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/emergency-info': typeof EmergencyInfoRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/live-map': typeof LiveMapRoute
  '/login': typeof LoginRoute
  '/nearby-facilities': typeof NearbyFacilitiesRoute
  '/signup': typeof SignupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/emergency-info'
    | '/forgot-password'
    | '/live-map'
    | '/login'
    | '/nearby-facilities'
    | '/signup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/emergency-info'
    | '/forgot-password'
    | '/live-map'
    | '/login'
    | '/nearby-facilities'
    | '/signup'
  id:
    | '__root__'
    | '/'
    | '/emergency-info'
    | '/forgot-password'
    | '/live-map'
    | '/login'
    | '/nearby-facilities'
    | '/signup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmergencyInfoRoute: typeof EmergencyInfoRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LiveMapRoute: typeof LiveMapRoute
  LoginRoute: typeof LoginRoute
  NearbyFacilitiesRoute: typeof NearbyFacilitiesRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nearby-facilities': {
      id: '/nearby-facilities'
      path: '/nearby-facilities'
      fullPath: '/nearby-facilities'
      preLoaderRoute: typeof NearbyFacilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-map': {
      id: '/live-map'
      path: '/live-map'
      fullPath: '/live-map'
      preLoaderRoute: typeof LiveMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency-info': {
      id: '/emergency-info'
      path: '/emergency-info'
      fullPath: '/emergency-info'
      preLoaderRoute: typeof EmergencyInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmergencyInfoRoute: EmergencyInfoRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LiveMapRoute: LiveMapRoute,
  LoginRoute: LoginRoute,
  NearbyFacilitiesRoute: NearbyFacilitiesRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
